# Generated by Django 3.0.6 on 2020-07-07 13:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('work_college', models.CharField(choices=[('文學院', '文學院'), ('藝術學院', '藝術學院'), ('傳播學院', '傳播學院'), ('教育學院', '教育學院'), ('醫學院', '醫學院'), ('理工學院', '理工學院'), ('外國語文學院', '外國語文學院'), ('民生學院', '民生學院'), ('法律學院', '法律學院'), ('社會科學院', '社會科學院'), ('管理學院', '管理學院'), ('織品服裝學院', '織品服裝學院')], max_length=50)),
                ('work_department', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('pdf_file', models.FileField(blank=True, upload_to='pdf_file')),
                ('video_url', models.URLField(blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-created_date',),
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studID', models.CharField(max_length=200, unique=True)),
                ('choice_workTitle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolios.Work')),
            ],
        ),
    ]
