# Generated by Django 3.0.6 on 2020-05-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-created_date',)},
        ),
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(blank=True, upload_to='post_files'),
        ),
    ]
