# Generated by Django 3.0.6 on 2020-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolios', '0002_auto_20200510_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='file',
            field=models.FileField(blank=True, upload_to='files'),
        ),
    ]
