# Generated by Django 3.0.6 on 2020-07-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=40, unique=True)),
                ('fullName', models.CharField(max_length=200, verbose_name='中文全名')),
                ('department', models.CharField(max_length=200, verbose_name='系所')),
                ('is_active', models.BooleanField(default=True, verbose_name='啟用')),
                ('is_admin', models.BooleanField(default=False, verbose_name='管理員')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
