# Generated by Django 3.0.6 on 2020-06-07 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studID', models.CharField(max_length=200)),
                ('fullName', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('choice_text', models.CharField(max_length=200)),
            ],
        ),
    ]
