# Generated by Django 3.0.6 on 2020-07-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=200, verbose_name='系所'),
        ),
        migrations.AlterField(
            model_name='user',
            name='fullName',
            field=models.CharField(blank=True, max_length=200, verbose_name='中文全名'),
        ),
    ]
