# Generated by Django 3.0.6 on 2020-06-07 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200607_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='studID',
        ),
    ]
