# Generated by Django 3.0.6 on 2020-09-11 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200720_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor_Infos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('page_visited', models.TextField()),
                ('event_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
